#Use base image (Ubuntu)
FROM ubuntu:20.04
#Maintainer info
LABEL maintainer="POC"
#Install required packages (Java + wget + unzip)
RUN apt-get update && apt-get install -y \
    openjdk-11-jdk \
    wget \
    unzip \
    && rm -rf /var/lib/apt/lists/*
#Set environment variables for Java & Tomcat
ENV CATALINA_HOME=/opt/tomcat
ENV PATH=$CATALINA_HOME/bin:$PATH
#Download & install Tomcat
RUN wget https://downloads.apache.org/tomcat/tomcat-9/v9.0.97/bin/apache-tomcat-9.0.97.tar.gz \           
    && mkdir -p $CATALINA_HOME \
    && tar xvf apache-tomcat-9.0.97.tar.gz -C $CATALINA_HOME --strip-components=1 \
    && rm apache-tomcat-9.0.97.tar.gz
#Expose Tomcat port
EXPOSE 8080   
#Start Tomcat
CMD ["catalina.sh", "run"]                  
