apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/ayushicybage/frontend:latest   # ✅ single-line image format
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_API_URL
              value: http://backend:5000/api
