apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.backend.service.port | default 8080 | int }}
      targetPort: {{ .Values.backend.service.port | default 8080 | int }}
