apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          ports:
            - containerPort: {{ .Values.backend.service.port | int }}
          env:
            {{- range .Values.backend.env }}
            - name: "{{ .name }}"
              {{- if .value }}
              value: "{{ .value }}"
              {{- else if .valueFrom }}
              valueFrom:
                secretKeyRef:
                  name: "{{ .valueFrom.secretKeyRef.name }}"
                  key: "{{ .valueFrom.secretKeyRef.key }}"
              {{- end }}
          {{- end }}
        

 