apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.frontend.service.port | default 80 | int }}
      targetPort: {{ .Values.frontend.service.port | default 80 | int }}
